import '../../../../core/utils/app_color.dart';
import 'task_item.dart';

List<TaskItem> mockTaskItems() => [
      TaskItem(
        id: 'TSK-001',
        category: 'تعليمات العمل بالموقع',
        title:
            'إنشاء مدن للورود والنباتات العطرية بمنطقة جازان (أحد المسارحة)',
        owner: '',
        duration: '2 days',
        statusLabel: 'جديد',
        status: 'new',
        indicatorColor: AppColor.kPrimaryColor,
        badgeColor: AppColor.kPrimaryColor.withOpacity(0.12),
        badgeTextColor: AppColor.kPrimaryColor,
        requestDate: '09-06-2026',
        contractor: 'مؤسسة طويق العمرانية للمقاولات',
        serialNumber: '4',
        revisionNumber: '0',
        currentTask: 'New task',
        specialization: 'عام',
        deliveryStatus: 'لا يوجد',
        description: 'لا يوجد',
      ),
      TaskItem(
        id: 'TSK-002',
        category: 'الدراسات والتصاميم',
        title: 'Environmental Impact Survey',
        owner: 'Sarah K.',
        duration: '5 days',
        statusLabel: '5 days',
        status: 'new',
        indicatorColor: AppColor.kGoldColor,
        badgeColor: AppColor.kGoldColor.withOpacity(0.12),
        badgeTextColor: AppColor.kGoldColor,
        requestDate: '01-05-2026',
        contractor: 'شركة البناء المتقدم',
        serialNumber: '12',
        revisionNumber: '1',
        currentTask: 'Review docs',
        specialization: 'بيئي',
        deliveryStatus: 'قيد المراجعة',
        description: 'مسح الأثر البيئي للموقع',
      ),
      TaskItem(
        id: 'TSK-003',
        category: 'التنفيذ',
        title: 'Marine Life Observation',
        owner: 'Dr. Ahmed',
        duration: 'Active',
        statusLabel: 'Active',
        status: 'in_progress',
        indicatorColor: AppColor.kPrimaryColor,
        badgeColor: AppColor.kPrimaryColor.withOpacity(0.12),
        badgeTextColor: AppColor.kPrimaryColor,
        requestDate: '15-04-2026',
        contractor: 'مؤسسة الخليج البحرية',
        serialNumber: '7',
        revisionNumber: '2',
        currentTask: 'Field work',
        specialization: 'بحري',
        deliveryStatus: 'قيد التسليم',
        description: 'مراقبة الحياة البحرية',
      ),
      TaskItem(
        id: 'TSK-004',
        category: 'التخطيط',
        title: 'Resource Allocation Map',
        owner: 'Layla M.',
        duration: 'Waiting',
        statusLabel: 'Waiting',
        status: 'pending',
        indicatorColor: AppColor.kGoldColor,
        badgeColor: AppColor.kGoldColor.withOpacity(0.12),
        badgeTextColor: AppColor.kGoldColor,
        requestDate: '20-03-2026',
        contractor: 'مؤسسة طويق العمرانية للمقاولات',
        serialNumber: '3',
        revisionNumber: '0',
        currentTask: 'Pending approval',
        specialization: 'عام',
        deliveryStatus: 'بانتظار المراجعة',
        description: 'خريطة توزيع الموارد',
      ),
      TaskItem(
        id: 'TSK-005',
        category: 'الاستلام',
        title: 'Initial Site Inspection',
        owner: 'Ali Al-Harbi',
        duration: 'Completed',
        statusLabel: 'Completed',
        status: 'ended',
        indicatorColor: AppColor.kGrayTextColor,
        badgeColor: AppColor.kPrimaryColor.withOpacity(0.12),
        badgeTextColor: AppColor.kPrimaryColor,
        requestDate: '10-02-2026',
        contractor: 'شركة البناء المتقدم',
        serialNumber: '1',
        revisionNumber: '0',
        currentTask: 'Done',
        specialization: 'عام',
        deliveryStatus: 'تم التسليم',
        description: 'معاينة أولية للموقع',
      ),
    ];

const List<({String key, String title})> taskKanbanColumns = [
  (key: 'new', title: 'جديد'),
  (key: 'in_progress', title: 'قيد التنفيذ'),
  (key: 'pending', title: 'قيد المراجعة'),
  (key: 'ended', title: 'مكتمل'),
];
